language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: devel
      services: mongodb
      r_check_args: '--run-donttest'
    - os: osx
      osx_image: xcode9.3
      brew_packages: openssl@1.1
      before_install:
        - brew install mongodb
        - brew services start mongodb
      r_check_args: '--run-donttest'
      warnings_are_errors: false
    - os: osx
      osx_image: xcode9.3
      brew_packages: openssl
      warnings_are_errors: false
    - os: osx
      osx_image: xcode9.3
      brew_packages: libressl
      warnings_are_errors: false
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      latex: false
      warnings_are_errors: false

addons:
  apt:
    packages:
    - libssl-dev
    - libsasl2-dev
    - libicu-dev
    - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov(type = "all")'; fi
