language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
    - libssl-dev
    - libsasl2-dev
    - libicu-dev

r_github_packages:
  - jeroenooms/jsonlite
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
