language: r

warnings_are_errors: true
#r_check_revdep: true

apt_packages:
  - libssl-dev
  - libsasl2-dev

r_github_packages:
  - jeroenooms/stringi
  - jeroenooms/jsonlite

notifications:
  email:
    on_success: change
    on_failure: change
